### ISSUE TITLE
The JWS signature MUST have a payload of a valid JSON serialization of the complete

### ISSUE THREAD

**Issue by rasmuseeg** [bitflipping-net/doctrina-lrs#24]
```
### The JWS signature MUST have a payload of a valid JSON serialization of the complete Statement before the signature was added. (Data 2.6.s4.b3, XAPI-00116)
POST /xapi/statements HTTP/1.1
Content-Type: multipart/mixed; boundary=-------------1339291747
X-Experience-API-Version: 1.0.3
Authorization: Basic YWRtaW5AZXhhbXBsZS5jb206ektSNGdrWU5IUDV0dkg=
host: localhost:52209
content-length: 1708
Connection: close


---------------1339291747
Content-Type:application/json

{"actor":{"objectType":"Agent","name":"xAPI mbox","mbox":"mailto:xapi@adlnet.gov"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attended","display":{"en-GB":"attended","en-US":"attended"}},"object":{"objectType":"Activity","id":"http://www.example.com/meetings/occurances/34534"},"id":"7293c64d-e833-4f60-a062-883d41ee2daa","attachments":[{"usageType":"http://adlnet.gov/expapi/attachments/signature","display":{"en-US":"Signed by the Test Suite"},"description":{"en-US":"Signed by the Test Suite"},"contentType":"application/octet-stream","length":796,"sha2":"e9d09a57a39a6b620fbd9b33feb8c31752958749e1d142bedd4767e41522e82a"}]}
---------------1339291747
Content-Type:application/octet-stream
Content-Transfer-Encoding:binary
X-Experience-API-Hash:e9d09a57a39a6b620fbd9b33feb8c31752958749e1d142bedd4767e41522e82a

eyJhbGciOiJSUzI1NiJ9.eydhY3RvciI6eyJvYmplY3RUeXBlIjoiQWdlbnQiLCJuYW1lIjoieEFQSSBtYm94IiwibWJveCI6Im1haWx0bzp4YXBpQGFkbG5ldC5nb3YifSwidmVyYiI6eyJpZCI6Imh0dHA6Ly9hZGxuZXQuZ292L2V4cGFwaS92ZXJicy9hdHRlbmRlZCIsImRpc3BsYXkiOnsiZW4tR0IiOiJhdHRlbmRlZCIsImVuLVVTIjoiYXR0ZW5kZWQifX0sIm9iamVjdCI6eyJvYmplY3RUeXBlIjoiQWN0aXZpdHkiLCJpZCI6Imh0dHA6Ly93d3cuZXhhbXBsZS5jb20vbWVldGluZ3Mvb2NjdXJhbmNlcy8zNDUzNCJ9LCJpZCI6IjcyOTNjNjRkLWU4MzMtNGY2MC1hMDYyLTg4M2Q0MWVlMmRhYSJ9.kMWiSoyxGqN9e3PRcjcj7Z4RAcVKrafVaNlNMmYV92UE2nUB0nfKxhO4UICRG92EAaTAfnTtJyaDo8nERXOirYI6b3OYtMh5gZg9EYuDWAjOi5bLu_u1aTN59VYMCJsyHwaChMfj7PdhroJeQYbGKCDV6d9SAClPPxGU1VERaI73pz-IY1Qk7vRM1xwMuUFcdVx3eY0LkBYLnoKX6x2qPInknb5OBNIpzBJR9tChiOUeQZbEAKy1YiWn9BRKXrHBm-32FoM0K5To85eX0cV7DERlKnGtxBbrB456v5CCVKmcisoSq1JBSHevO1OouShsI5_kxifJKOn9b8Ir4_5piw
---------------1339291747--
```

**Comment by jerrygoguen** [comment]
Ramus,

It has been a while since we communicated.  I see you have done some more work.  I hope all is well with you.  I am still very interested in doing something with you.  I had started to put together a short arrangement proposal.  I also locked down a couple of variations of the Doctrina-lrs domain names.  In addition I was about to begin some work on Doctrina with my team then we got a large contract for a highly custom classroom and virtual classroom management system prior to Covid-19 for a organization with over 1 million users.  They ended up getting some federal grants and are focused on getting their workforce safely  back to work. We are putting all of our energy into this project.

I would like to integrate what we have done for them because it can also help other organizations with your LRS.  I am still willing to pay for the entire Azure infrastructure for your open source LRS.  The issue I am having is people resource related as I do not have anyone freed up to work on this.   I am wondering if you would be interested in a relationship in which I provide you a grant of $1000 US per month to get the LRS onto Azure and help us connect what we have to it so we can support a simple interface to xapi content.

I am interested to discuss the possibility after it is all working if it would make sense to offer Doctrina at a nominal fee (less than commercial LRS fees) for organizations to use the LRS without having to download and deploy it themselves.

Let me know what you think.

Jerry Goguen

Jerry Goguen
CEO/CTO
Intralearn Software
508-3783-2277 X 6199

www.intralearn.com
